name: Modern Sapiens
favicon: null
layout_spectrum: 0.9309691577218473
typography_spectrum: 0.35029555880464613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9399405899457633
  lightness: 0.3681610841304064
  saturation: 0.4451681354548782
  rhythmicContrast: 0.5097347814589739
purpose: []
