name: Modern Sapiens
favicon: null
layout_spectrum: 0.2429
typography_spectrum: 0.35029555880464613
title: Helping Humans Cope with Technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#8c8a8b'
    - '#dcdcdc'
    - '#5f5f5f'
  brandStrength: 1
  lightness: 0.3681610841304064
  saturation: 0.4451681354548782
  rhythmicContrast: 0.5097347814589739
purpose: []
